version: '3.8'

services:
  aboard-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - .:/app
    command: npm run start:dev
    depends_on:
      - aboard-db
  aboard-db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aboard_admin
      POSTGRES_PASSWORD: aboard_password
      POSTGRES_DB: aboard_db
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local